version: 2.1
jobs:
  build_test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout # checkout source code to working directory
      - run:
          name: Build package
          command: | # create whl and use pipenv to install dependencies
            sudo add-apt-repository universe -y
            sudo apt-get update
            sudo apt install -y python3-pip
            python3 -m pip install virtualenv
            python3 -m pip install pytest
            python3 -m pip install --upgrade build
            python3 -m build
            pip install dist/smalltools_st-0.0.4-py3-none-any.whl
      - run:
          name: Run tests
          command: | # Run test suite
            pytest
  test_pypi_publish:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout # checkout source code to working directory
      - run:
          name: Build package and publish to TestPyPI
          command: | # create whl, install twine and publish to Test PyPI
            sudo add-apt-repository universe -y
            sudo apt-get update
            sudo apt install -y python3-pip
            python3 -m pip install virtualenv
            python3 -m pip install --upgrade build
            python3 -m build
            python3 -m pip install --upgrade twine
            python3 -m twine upload --repository testpypi dist/*
  pypi_publish:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout # checkout source code to working directory
      - run:
          name: Build package and publish to PyPI
          command: | # create whl, install twine and publish to PyPI
            sudo add-apt-repository universe -y
            sudo apt-get update
            sudo apt install -y python3-pip
            python3 -m pip install virtualenv
            python3 -m pip install --upgrade build
            python3 -m build
            python3 -m pip install --upgrade twine
            python3 -m twine upload dist/*
workflows:
  build_test_publish:
    jobs:
      - build_test
      - test_pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - develop
      - pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - main