version: 2.1
orbs:
  node: circleci/node@4.3
  gh: circleci/github-cli@1.0
jobs:
  build_test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout # checkout source code to working directory
      - run:
          name: Build package
          command: | # create whl and use pipenv to install dependencies
            sudo add-apt-repository universe -y
            sudo apt-get update
            sudo apt install -y python3-pip
            python3 -m pip install virtualenv
            python3 -m pip install pytest
            python3 -m pip install --upgrade build
            python3 -m build
            pip install dist/smalltools_st-0.0.6-py3-none-any.whl
      - run:
          name: Run tests
          command: | # Run test suite
            pytest
  test_pypi_publish:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout # checkout source code to working directory
      - run:
          name: Build package and publish to TestPyPI
          command: | # create whl, install twine and publish to Test PyPI
            sudo add-apt-repository universe -y
            sudo apt-get update
            sudo apt install -y python3-pip
            python3 -m pip install virtualenv
            python3 -m pip install --upgrade build
            python3 -m build
            python3 -m pip install --upgrade twine
            export TWINE_USERNAME=$TEST_TWINE_USERNAME
            export TWINE_PASSWORD=$TEST_TWINE_PASSWORD
            python3 -m twine upload --repository testpypi dist/*
  pypi_publish:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout # checkout source code to working directory
      - run:
          name: Build package and publish to PyPI
          command: | # create whl, install twine and publish to PyPI
            sudo add-apt-repository universe -y
            sudo apt-get update
            sudo apt install -y python3-pip
            python3 -m pip install virtualenv
            python3 -m pip install --upgrade build
            python3 -m build
            python3 -m pip install --upgrade twine
            python3 -m twine upload dist/*
workflows:
  build_test_publish:
    jobs:
      - build_test
      - test_pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - development
      - pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - main
      - gh/release:
          notes-file: CHANGELOG.md
          tag: 0.0.6
          title: "Added: Automation with CircleCI its here!"
          requires:
            - pypi_publish
          context:
            - GITHUB_CREDENTIALS
          filters:
            branches:
              only:
                - main